### ISSUE TITLE
About AudioDataset and AudioDataLoader

### ISSUE THREAD

**Issue by Reid-Cui7** [Zhongyang-debug/Attention-Is-All-You-Need-In-Speech-Separation#2]
Thanks for your great work!
In train.py, you import AudioDataset and AudioDataLoader from dataset.data
Does data.py the same as Kaituo Xu's data.py, which is widely used in speech separation ?

**Comment by Zhongyang-debug** [comment]
It's the same.You can try writing it down.

**Comment by Reid-Cui7** [comment]
Thanks
