### ISSUE TITLE
About hyperparameter in train.json5

### ISSUE THREAD

**Issue by Reid-Cui7** [Zhongyang-debug/Attention-Is-All-You-Need-In-Speech-Separation#3]
In train.json5, the model's hyperparameter part does not match, though from the Sepformer __init__(), one can infer the hyperparameter and change the train.json5 counterpart.

Another question, does this model use the same logic with DPRNN ? the intra and the inter path or something like this.
I've tried the DPRNN, it was super slow in training, and the result was not that good, what about your results ?

Thank you, I am a new fish 😊

**Comment by Zhongyang-debug** [comment]
“Another question, does this model use the same logic with DPRNN ? the intra and the inter path or something like this.
I've tried the DPRNN, it was super slow in training, and the result was not that good, what about your results ?”

It is the same as DPRNN, and the training results are good.

**Comment by Zhongyang-debug** [comment]
“In train.json5, the model's hyperparameter part does not match, though from the Sepformer init(), one can infer the hyperparameter and change the train.json5 counterpart.”

This needs to be corrected.

**Comment by Zhongyang-debug** [comment]
“In train.json5, the model's hyperparameter part does not match, though from the Sepformer init(), one can infer the hyperparameter and change the train.json5 counterpart.”

**Comment by Zhongyang-debug** [comment]
“In train.json5, the model's hyperparameter part does not match, though from the Sepformer init(), one can infer the hyperparameter and change the train.json5 counterpart.”

This part has been corrected. You'd better understand it yourself.
