### ISSUE TITLE
About Positional encoding

### ISSUE THREAD

**Issue by Reid-Cui7** [Zhongyang-debug/Attention-Is-All-You-Need-In-Speech-Separation#5]
In class PositionalEncoding, the forward function already return x + Variable(self.pe[:, :x.size(1)], requires_grad=False)
while in class DPTBlock, the forward function computes row_z1 = row_z + self.intra_PositionalEncoding(row_z) 
does this make the input double added ?

Thank you

**Comment by Zhongyang-debug** [comment]
Only need to be used once.

**Comment by Zhongyang-debug** [comment]
How does this model work?  According to the paper parameters, I can't run it.
kernel_size=24
local_b=5

**Comment by Reid-Cui7** [comment]
According to your latest update code, I still think the input is added twice, if we pass the parameter row_z to class PositionalEncoding, it returns us row_z+ encoded part, while row_z = row_z + (returned part), is it add twice ? I am little confused here.
I tried the new code, but even when testing model.py, I run out of memory/(ㄒoㄒ)/~~(on server)
I have tried the dprnn conv-tas dpt... honesly, I did not get the desired result, I used part of the wsj dataset,  the si-snr is same with the paper claims, but what about using the full dataset ? I think the result will fall.
I got best result in dptnet, but it runs really slow😀

**Comment by Reid-Cui7** [comment]
and no matter si-snr high or low, the sounds feel almost the same(*^_^*)
what about your result ?

**Comment by Zhongyang-debug** [comment]
https://github.com/kaituoxu/Speech-Transformer/blob/master/src/transformer/module.py
Take a look at this, your idea is right, thank you.

**Comment by Zhongyang-debug** [comment]
I worked better on the WSJ0（only two speakers） dataset.

**Comment by Reid-Cui7** [comment]
Thank you!
I appreciate your work, it helps me a lot, keep in touch(*^_^*)
